services:
  - type: web
    name: python-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app"  # or whatever you use
    envVars:
      - key: PYTHON_VERSION
        value: 3.10